RISC0 version bump and various fixes
polybase/zk-benchmarks pull request #45
Opened 2023-09-19 22:23 UTC by capossele

Few suggestions:
- bump `risc0-zkvm` to 0.18
- simplify code
- fix how the input is fed to the guest on the merkle examples

In general running the prover with CPU vs metal vs CUDA can be achieved by just enabling the feature e.g., `-F metal`. However, I've quickly tested with metal and it seems that somehow does not work well with nix.

2023-09-22 05:41 UTC, mateuszmlc requested changes
Thanks! Looks good. Could you also update the benchmarks.yaml to remove the multi-cpu, metal args, since they're not used anymore?

2023-09-22 11:02 UTC, mateuszmlc approved these changes

2023-09-22 17:26 UTC, cameron1024 approved these changes
Thanks for this, looks good 🙏

2023-09-24 01:31 UTC, merged

2023-09-24 05:57 UTC, calummoore commented
Thanks for the PR @capossele 👍